# Generated by Django 3.1.5 on 2022-04-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('paymenttype', models.CharField(max_length=255)),
                ('paymentamount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roombookings',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('customername', models.CharField(blank=True, max_length=500, null=True)),
                ('customeraddress', models.CharField(blank=True, max_length=550, null=True)),
                ('bookingfrom', models.DateField(blank=True, null=True)),
                ('bookingto', models.DateField(blank=True, null=True)),
                ('noofguests', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roombookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('roomid', models.AutoField(primary_key=True, serialize=False)),
                ('roomnumber', models.IntegerField()),
                ('roomprice', models.IntegerField()),
                ('roomtype', models.CharField(max_length=255)),
                ('roomcapacity', models.IntegerField()),
            ],
            options={
                'db_table': 'rooms',
                'managed': False,
            },
        ),
    ]
